version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: supermarket_user
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: supermarket_db
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql

